import type { CanonicalRule, CanonicalContext, GeneratedFile } from '../core/types.js';
import { BANNER_TEXT } from '../core/templates.js';

export function formatBanner(commentPrefix = '<!--', commentSuffix = '-->'): string {
  if (commentPrefix === '<!--') {
    return BANNER_TEXT;
  }
  return `${commentPrefix} AUTO-GENERATED BY SYNCYTIUM-MD ${commentSuffix}\n${commentPrefix} Source of truth: .syncytium/ ${commentSuffix}\n\n`;
}

export function compileRulesMarkdown(rules: CanonicalRule[], title = 'Project Rules & Guidelines'): string {
  let output = `# ${title}\n\n`;

  for (const rule of rules) {
    output += `## 📌 ${rule.title}\n`;
    if (rule.description) {
      output += `> *${rule.description}*\n\n`;
    }
    if (rule.globs && rule.globs.length > 0) {
      output += `**Target Files:** \`${rule.globs.join(', ')}\`\n\n`;
    }
    output += `${rule.content}\n\n---\n\n`;
  }

  return output.trim();
}

export function compileHandoffSummary(context: CanonicalContext): string {
  const h = context.handoff;
  return `### 🤝 Live Handoff Status
- **Active Agent:** \`${h.activeAgent}\` (Next: \`${h.nextAgent || 'Any'}\`)
- **Status:** \`${h.status.toUpperCase()}\`
- **Current Goal:** ${h.goal}
- **Pending Tasks:**
${h.pendingTasks.map(t => `  - [ ] ${t}`).join('\n') || '  - None'}
- **Notes:** ${h.contextNotes || 'None'}
`;
}
