import type { CanonicalRule, CanonicalContext, GeneratedFile } from '../core/types.js';
import { BANNER_TEXT } from '../core/templates.js';
import { slugify } from '../core/paths.js';

/** Stable filename fragment for a rule, safe on every platform. */
export function ruleFileId(rule: Pick<CanonicalRule, 'id'>): string {
  return slugify(rule.id, 'rule');
}

export function formatBanner(commentPrefix = '<!--', commentSuffix = '-->'): string {
  if (commentPrefix === '<!--') {
    return BANNER_TEXT;
  }
  return `${commentPrefix} AUTO-GENERATED BY SYNCYTIUM-MD ${commentSuffix}\n${commentPrefix} Source of truth: .syncytium/ ${commentSuffix}\n\n`;
}

export function compileRulesMarkdown(
  rules: CanonicalRule[],
  title = 'Project Rules & Guidelines'
): string {
  let output = `# ${title}\n\n`;

  for (const rule of rules) {
    output += `## 📌 ${rule.title}\n`;
    if (rule.description) {
      output += `> *${rule.description}*\n\n`;
    }
    if (rule.globs && rule.globs.length > 0) {
      output += `**Target Files:** \`${rule.globs.join(', ')}\`\n\n`;
    } else if (rule.alwaysApply === false) {
      output += `**Target Files:** _not declared - set \`globs\` in the rule frontmatter_\n\n`;
    }
    if (rule.priority) {
      output += `**Priority:** ${rule.priority}\n\n`;
    }
    output += `${rule.content}\n\n---\n\n`;
  }

  return output.trim();
}

/** Optional at-a-glance index of rule ids, useful for long rule sets. */
export function compileRuleIndex(rules: CanonicalRule[]): string {
  if (rules.length === 0) return '';
  const lines = rules.map(rule => {
    const scope = rule.alwaysApply === false ? 'glob-scoped' : 'always';
    const tags = rule.tags && rule.tags.length > 0 ? ` _(${rule.tags.join(', ')})_` : '';
    return `- \`${ruleFileId(rule)}\` — **${rule.title}** · _${scope}_${tags}`;
  });
  return `## 🗂️ Rule Index\n\n${lines.join('\n')}\n\n---\n\n`;
}

export function compileHandoffSummary(context: CanonicalContext): string {
  const h = context.handoff;
  const touched = h.touchedFiles.slice(-8);
  return `### 🤝 Live Handoff Status
- **Active Agent:** \`${h.activeAgent}\` (Next: \`${h.nextAgent || 'Any'}\`)
- **Status:** \`${h.status.toUpperCase()}\`
- **Current Goal:** ${h.goal || '_No active goal recorded._'}
- **Pending Tasks:**
${h.pendingTasks.map(t => `  - [ ] ${t}`).join('\n') || '  - None'}
${touched.length > 0 ? `- **Recently Touched:**\n${touched.map(f => `  - \`${f}\``).join('\n')}\n` : ''}- **Notes:** ${h.contextNotes || 'None'}
- **Last Updated:** ${h.lastUpdated}
`;
}

export function compileArchitecture(context: CanonicalContext, heading = 'Architecture'): string {
  if (!context.architecture || !context.architecture.trim()) return '';
  return `## ${heading}\n\n${context.architecture.trim()}\n\n---\n\n`;
}

export function compileDecisions(context: CanonicalContext, limit = 8): string {
  if (!context.decisions || context.decisions.length === 0) return '';
  let out = '## 🧠 Key Decisions (ADR)\n\n';
  for (const d of context.decisions.slice(0, limit)) {
    out += `- **[${d.id}] ${d.title}:** ${d.decision} _(${d.status}, ${d.date})_\n`;
  }
  if (context.decisions.length > limit) {
    out += `- _…and ${context.decisions.length - limit} more in \`.syncytium/memory/decisions.md\`_\n`;
  }
  return `${out}\n`;
}

/** Strips a banner from generated content so user sections can be diffed. */
export function stripGeneratedSections(content: string): string {
  return content.replace(/^<!--[\s\S]*?SYNCYTIUM-MD[\s\S]*?-->\n?/m, '');
}

/** Marker line that separates generated output from user-authored content. */
export const PRESERVED_SECTION_MARKER = 'Syncytium preserved user section';

/** Detects the comment style used by a file so we can round-trip markers. */
function commentPrefixFor(content: string): string {
  const first = content.split('\n', 1)[0] ?? '';
  if (first.includes('#!') || first.trimStart().startsWith('#')) return '#';
  if (first.includes('<!--')) return '<!--';
  if (first.trimStart().startsWith('//')) return '//';
  return '<!--';
}

function markerLine(prefix: string): string {
  if (prefix === '<!--') return '<!-- ===== Syncytium preserved user section ===== -->';
  if (prefix === '//') return '// ===== Syncytium preserved user section =====';
  return '# ===== Syncytium preserved user section =====';
}

/**
 * Merges user-authored content that lives below the generated banner.
 * Only the trailing section after the marker is preserved, and only when
 * `preserveCustomSections` is enabled. The comment style of the existing file
 * is reused so YAML/JSON-adjacent targets stay parseable.
 */
export function mergeUserSection(generated: string, existing: string | null): string {
  if (!existing) return generated;
  const preserved = extractUserSection(existing);
  if (!preserved) return generated;
  const marker = markerLine(commentPrefixFor(existing));
  return `${generated.trimEnd()}\n\n${marker}\n\n${preserved}\n`;
}

export function extractUserSection(existing: string): string {
  const index = existing.indexOf(PRESERVED_SECTION_MARKER);
  if (index === -1) return '';
  const lineEnd = existing.indexOf('\n', index);
  return existing
    .slice(lineEnd === -1 ? existing.length : lineEnd + 1)
    .trim();
}

/**
 * Removes the preserved user section so a re-generated file compares equal to
 * what is on disk. Without this, a legitimately preserved section would show up
 * as permanent drift and fail `diff --check`.
 */
export function stripPreservedSection(content: string): string {
  const index = content.indexOf(PRESERVED_SECTION_MARKER);
  if (index === -1) return content;
  const lineStart = content.lastIndexOf('\n', index) + 1;
  return content.slice(0, lineStart).trimEnd();
}

export function makeFile(
  relativePath: string,
  content: string,
  description: string,
  adapterId: string
): GeneratedFile {
  return { relativePath, content, description, adapterId };
}
