import type { AgentAdapter, CanonicalContext, GeneratedFile } from '../../core/types.js';
import {
  formatBanner,
  compileRulesMarkdown,
  compileRuleIndex,
  compileHandoffSummary,
  compileArchitecture,
  compileDecisions,
  makeFile
} from '../base.js';

/**
 * `AGENTS.md` is the emerging cross-vendor convention (Codex CLI, OpenAI Codex,
 * Aider, and many OSS agent runners read it). Keeping it separate from
 * `AGENT.md` avoids clobbering a user's singular-`AGENT.md` file.
 */
export class AgentsAdapter implements AgentAdapter {
  readonly id = 'agents';
  readonly name = 'AGENTS.md Standard';
  readonly category = 'agent' as const;
  readonly description = 'Universal AGENTS.md context file (Codex CLI and AGENTS.md-aware agents)';
  readonly defaultTargetFiles = ['AGENTS.md'];

  async generate(context: CanonicalContext): Promise<GeneratedFile[]> {
    const emitIndex = context.config?.options.emitRuleIndex ?? false;

    let content = formatBanner();
    content += `# AGENTS.md - ${context.projectName}\n\n`;
    content += `> Universal agent instructions generated by SyncytiumMD. Source of truth: \`.syncytium/\`.\n\n`;
    content += `${compileHandoffSummary(context)}\n\n---\n\n`;
    content += compileArchitecture(context, 'System Architecture');
    if (emitIndex) content += compileRuleIndex(context.rules);
    content += `${compileRulesMarkdown(context.rules, 'Engineering Guidelines')}\n\n`;
    content += compileDecisions(context, 5);
    content += `## Working Agreement
1. Read \`.syncytium/HANDOFF.md\` before starting work; it holds the live goal and pending tasks.
2. Acquire the lease with \`syncytium lock acquire --agent "<name>"\`; release it before you finish.
3. After finishing, run \`syncytium handoff --from "<name>" -g "<goal>" -d "<done>" -t "<todo>"\`.
4. Never hand-edit generated files - change \`.syncytium/\` and run \`syncytium sync\`.
`;

    return [makeFile('AGENTS.md', content, 'Universal AGENTS.md context file', this.id)];
  }
}
