import type { AgentAdapter, CanonicalContext, GeneratedFile } from '../../core/types.js';
import {
  formatBanner,
  compileRulesMarkdown,
  compileHandoffSummary,
  compileArchitecture,
  compileRuleIndex,
  makeFile
} from '../base.js';

export class ClineAdapter implements AgentAdapter {
  readonly id = 'cline';
  readonly name = 'Cline / Roo Code';
  readonly category = 'extension' as const;
  readonly description = 'Autonomous agent instructions (.clinerules) plus Roo Code mode routing';
  readonly defaultTargetFiles = ['.clinerules', '.roomodes'];

  async generate(context: CanonicalContext): Promise<GeneratedFile[]> {
    const emitIndex = context.config?.options.emitRuleIndex ?? false;

    let content = formatBanner();
    content += `# Cline & Roo Code System Instructions - ${context.projectName}\n\n`;
    content += `> You are acting as an autonomous software engineer connected to SyncytiumMD.\n\n`;
    content += `${compileHandoffSummary(context)}\n\n---\n\n`;
    content += compileArchitecture(context, 'System Architecture');
    if (emitIndex) content += compileRuleIndex(context.rules);
    content += `${compileRulesMarkdown(context.rules, 'Project Execution Rules')}\n\n`;
    content += `## Syncytium Handoff Protocol
- Before completing your task, run \`syncytium handoff\` with your progress, touched files, and next tasks, or edit \`.syncytium/HANDOFF.md\`.
- Acquire the workspace lease with \`syncytium lock acquire --agent "<your name>"\` before editing, and release it when done.
- If you made architectural changes, record them with \`syncytium adr add\` (or \`.syncytium/memory/decisions.md\`).
- Never edit generated bridge files by hand; they are overwritten from \`.syncytium/\`.
`;

    const files: GeneratedFile[] = [
      makeFile('.clinerules', content, 'Cline / Roo Code rules file', this.id)
    ];

    // Roo Code reads YAML mode definitions, so this file needs `#` comments
    // rather than the HTML banner the Markdown targets use.
    const modeBody = `  - name: syncytium-architect
    description: Load the shared Syncytium context (.syncytium/) before making changes.
    roleDefinition: Always read .syncytium/HANDOFF.md, .syncytium/rules/ and .syncytium/memory/decisions.md first. Keep the bridge files in sync with \`syncytium sync\`.
    customInstructions: |
      ${context.projectName} canonical rules are defined in .clinerules (generated by SyncytiumMD). Treat them as the single source of truth and never contradict them.
    groups:
      - read
      - edit
`;
    files.push(
      makeFile(
        '.roomodes',
        `${formatBanner('#', '')}customModes:\n${modeBody}`,
        'Roo Code custom mode definition (generated by SyncytiumMD)',
        this.id
      )
    );

    return files;
  }
}
