import type { AgentAdapter, CanonicalContext, GeneratedFile } from '../../core/types.js';
import {
  formatBanner,
  compileRulesMarkdown,
  compileHandoffSummary,
  compileArchitecture,
  compileDecisions,
  makeFile
} from '../base.js';

/**
 * Gemini CLI reads project context from `GEMINI.md` in the workspace root.
 *
 * We deliberately do NOT emit `.gemini/settings.json`: its schema is owned by
 * the CLI, and writing invented keys there risks breaking the user's own
 * configuration. `GEMINI.md` is the stable, documented integration point.
 */
export class GeminiAdapter implements AgentAdapter {
  readonly id = 'gemini';
  readonly name = 'Gemini CLI';
  readonly category = 'cli' as const;
  readonly description = 'Gemini CLI project context (GEMINI.md)';
  readonly defaultTargetFiles = ['GEMINI.md'];

  async generate(context: CanonicalContext): Promise<GeneratedFile[]> {
    let content = formatBanner();
    content += `# GEMINI.md - ${context.projectName}\n\n`;
    content += `> Project context for the Gemini CLI, generated by SyncytiumMD.\n`;
    content += `> Source of truth: \`.syncytium/\` - edit that, then run \`syncytium sync\`.\n\n`;
    content += `${compileHandoffSummary(context)}\n\n---\n\n`;
    content += compileArchitecture(context, 'System Architecture');
    content += `${compileRulesMarkdown(context.rules, 'Engineering Guidelines')}\n\n`;
    content += compileDecisions(context, 5);
    content += `## Working Agreement
1. Read \`.syncytium/HANDOFF.md\` first: it holds the live goal and pending tasks.
2. Take the lease with \`syncytium lock acquire --agent "Gemini"\`, release it when done.
3. Report back with \`syncytium handoff --from "Gemini" -g "<goal>" -d "<done>" -t "<todo>"\`.
4. Never hand-edit this file; it is overwritten from \`.syncytium/\`.
`;

    return [makeFile('GEMINI.md', content, 'Gemini CLI project context', this.id)];
  }
}
