import type { CanonicalRule, MemoryDecision, HandoffState } from './types.js';
import type { Stack } from './schemas.js';

export const DEFAULT_CONFIG = {
  version: '2.0.0',
  projectName: 'MyProject',
  enabledAdapters: [
    'cursor',
    'claude',
    'copilot',
    'cline',
    'antigravity',
    'windsurf',
    'trae',
    'opencode',
    'agents',
    'gemini'
  ],
  customAdapters: [] as unknown[],
  options: {
    addSyncytiumBanner: true,
    preserveCustomSections: true,
    emitRuleIndex: false,
    pruneOrphans: true,
    enforceLock: false
  }
};

export const INITIAL_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'Code Style & Formatting',
    description: 'Enforce clean, readable, modern standards across the project',
    alwaysApply: true,
    tags: ['style', 'formatting'],
    content: `## Code Style Guidelines
- Write clean, modular, and self-documenting code.
- Always prefer strict types, immutable data structures, and pure functions where reasonable.
- Keep functions concise with a single responsibility.
- Preserve existing comments and documentation unless explicitly asked to modify them.
- Avoid unnecessary dependencies; prefer standard library APIs where possible.`
  },
  {
    id: 'testing-standards',
    title: 'Testing Standards & Verification',
    description: 'Quality assurance and test verification guidelines',
    globs: ['**/*.test.*', '**/*.spec.*', 'tests/**/*'],
    alwaysApply: false,
    tags: ['test', 'quality'],
    content: `## Testing Guidelines
- Write unit tests for all business logic and edge cases.
- Mock external network requests, timers, and heavy I/O in unit test suites.
- Verify tests pass before completing any implementation task.
- Follow the Arrange-Act-Assert pattern for test clarity.`
  },
  {
    id: 'security',
    title: 'Security & Safe Coding',
    description: 'Security rules, secrets handling, and sanitization',
    alwaysApply: true,
    tags: ['security', 'compliance'],
    content: `## Security Guidelines
- Never commit secrets, API keys, tokens, or credentials into source control.
- Validate all incoming user input and payloads against strong schemas.
- Prevent injection attacks (SQL, command execution, XSS, template injection).
- Use parameterized queries and sanitized output.`
  }
];

export const INITIAL_ARCHITECTURE = `# System Architecture & Technology Stack

## Overview
Describe the purpose of this project, its primary architectural patterns, and its system boundaries.

## Technology Stack
- **Runtime:** (fill in)
- **Frameworks:** (fill in)
- **Communication:** (fill in)

## Directory Layout
- \`src/\`: Source code and adapters
- \`.syncytium/\`: Single Source of Truth (SSoT) for all AI agents
  - \`rules/\`: Universal coding and architecture rules
  - \`memory/\`: Architectural decisions (ADRs), handoff history, agent lock
  - \`HANDOFF.md\`: Live agent state and task handoff
`;

export const INITIAL_DECISIONS: MemoryDecision[] = [
  {
    id: 'ADR-001',
    title: 'Adopt SyncytiumMD as Universal Context Bridge',
    status: 'accepted',
    date: new Date().toISOString().split('T')[0],
    context: 'Multiple AI agents and IDEs (Cursor, Claude Code, Copilot, Cline, Antigravity, etc.) are used concurrently, leading to fragmented context and duplicated rules.',
    decision: 'Use SyncytiumMD as the single source of truth (.syncytium/) to transpile and synchronize rules, memories, and handoff state across all AI coding tools.',
    consequences: 'All tools stay in sync with zero manual copy-pasting. Changes in rules propagate automatically to all connected IDEs and CLIs.'
  }
];

export const INITIAL_HANDOFF: HandoffState = {
  activeAgent: 'Human',
  nextAgent: 'Any AI Assistant (Cursor, Claude Code, Cline, Antigravity, etc.)',
  status: 'ready_for_review',
  goal: 'Initialize project structure and verify multi-agent Markdown bridges',
  completedWork: [
    'Initialized .syncytium/ single source of truth directory',
    'Created core rules: code style, testing, security',
    'Configured default adapters for Cursor, Claude, Copilot, Cline, Antigravity, Windsurf, Trae, OpenCode, AGENTS.md and GEMINI.md'
  ],
  pendingTasks: [
    'Run `syncytium sync` to generate bridge files',
    'Verify generated rule files across IDEs and CLIs',
    'Update HANDOFF.md when switching between AI assistants'
  ],
  touchedFiles: [
    '.syncytium/syncytium.config.json',
    '.syncytium/rules/code-style.md',
    '.syncytium/rules/security.md',
    '.syncytium/rules/testing-standards.md',
    '.syncytium/architecture.md',
    '.syncytium/memory/decisions.md',
    '.syncytium/HANDOFF.md'
  ],
  contextNotes: 'SyncytiumMD is initialized and ready. All AI agents reading this file should check pending tasks and update this file before ending their turn.',
  lastUpdated: new Date().toISOString()
};

export const BANNER_TEXT = `<!--
  ⚠️ AUTO-GENERATED BY SYNCYTIUM-MD ⚠️
  This file is automatically synchronized from .syncytium/
  Do not edit manually unless you plan to run reverse-sync.
  Source of truth: .syncytium/
-->
`;

export const BANNER_MARKER = 'AUTO-GENERATED BY SYNCYTIUM-MD';

export const CI_WORKFLOW_TEMPLATE = `name: SyncytiumMD Verification

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: syncytium-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Lint & Zero-Context-Drift Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Syncytium
        run: npm install -g syncytium-md

      - name: Validate canonical rules
        run: syncytium lint

      - name: Validate configuration schema
        run: syncytium validate

      # --check makes drift a non-zero exit code, so this gate can actually fail.
      - name: Verify zero context drift
        run: syncytium diff --check
`;

export const TYPESCRIPT_RULES: CanonicalRule[] = [
  ...INITIAL_RULES,
  {
    id: 'typescript-strictness',
    title: 'TypeScript Strict Mode & Types',
    description: 'Enforce strict TypeScript compiler options and clean type definitions',
    globs: ['**/*.ts', '**/*.tsx'],
    alwaysApply: false,
    tags: ['typescript', 'typing'],
    content: `## TypeScript Guidelines
- Enable and adhere to \`strict: true\` in tsconfig.
- Avoid using \`any\`; prefer \`unknown\`, generic type parameters, or explicit interfaces.
- Define explicit return types for public exported functions and API boundaries.
- Leverage Discriminated Unions for state management and error returns.`
  }
];

export const PYTHON_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'Python Code Style (PEP 8 & Modern Standards)',
    description: 'Enforce PEP 8, Black formatting, and modern typing standards',
    alwaysApply: true,
    tags: ['python', 'pep8', 'style'],
    content: `## Python Code Style Guidelines
- Strictly adhere to PEP 8 standards with 4-space indentation.
- Always include type hints (PEP 484) on function signatures.
- Prefer Python 3.10+ modern syntax (e.g. \`int | None\` instead of \`Optional[int]\`).
- Keep modules focused with explicit \`__all__\` exports where applicable.`
  },
  {
    id: 'testing-standards',
    title: 'Python Testing (pytest)',
    description: 'Testing guidelines for pytest suites',
    globs: ['tests/**/*.py', '**/*_test.py', 'test_*.py'],
    alwaysApply: false,
    tags: ['test', 'pytest'],
    content: `## Testing Guidelines (pytest)
- Structure tests using pytest fixtures and test functions prefixed with \`test_\`.
- Use \`pytest.mark.parametrize\` for boundary and edge-case testing.
- Never make live network requests in unit tests; use pytest-mock or responses.`
  },
  {
    id: 'security',
    title: 'Security & Sanitization',
    description: 'Safe python coding and environment variable practices',
    alwaysApply: true,
    tags: ['security', 'python'],
    content: `## Python Security Guidelines
- Load credentials via \`os.environ\` or \`pydantic-settings\`; never hardcode secrets.
- Avoid \`eval()\`, \`exec()\`, or unsafe \`yaml.load()\` (always use \`safe_load\`).
- Sanitize SQL queries with parameterized ORM bindings.`
  }
];

export const GO_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'Go Idiomatic Standards',
    description: 'Idiomatic Go style and error handling practices',
    alwaysApply: true,
    tags: ['go', 'golang', 'style'],
    content: `## Go Style Guidelines
- Follow standard Go formatting (\`gofmt\` / \`goimports\`).
- Explicit error handling: check errors immediately, do not ignore \`err\`.
- Keep package APIs minimal and package names concise and lowercase.
- Use context.Context as the first argument in long-running or network functions.`
  },
  {
    id: 'testing-standards',
    title: 'Go Testing Standards',
    description: 'Unit and table-driven testing in Go',
    globs: ['**/*_test.go'],
    alwaysApply: false,
    tags: ['test', 'go'],
    content: `## Go Testing Guidelines
- Use table-driven tests with \`t.Run()\` subtests.
- Clean up resources with \`t.Cleanup()\`.
- Verify race conditions using \`go test -race ./...\`.`
  },
  {
    id: 'security',
    title: 'Security & Concurrency',
    description: 'Safe concurrency and credential handling in Go',
    alwaysApply: true,
    tags: ['security', 'concurrency'],
    content: `## Go Security & Safety
- Guard concurrent state with sync.Mutex, sync.RWMutex, or channels.
- Avoid goroutine leaks by always respecting context cancellation.`
  }
];

export const RUST_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'Rust Idioms & Formatting',
    description: 'Idiomatic Rust, rustfmt compliance and ownership discipline',
    alwaysApply: true,
    tags: ['rust', 'style'],
    content: `## Rust Style Guidelines
- Always run \`cargo fmt\` and keep \`cargo clippy -- -D warnings\` clean.
- Prefer \`Result<T, E>\` and \`Option<T>\` over panics and sentinel values.
- Borrow before cloning; pass \`&str\` instead of \`String\` for read-only arguments.
- Document public items with \`///\` doc comments including a \`# Errors\` section for fallible APIs.`
  },
  {
    id: 'testing-standards',
    title: 'Rust Testing Standards',
    description: 'Unit and integration testing idioms for Rust',
    globs: ['**/tests/**/*.rs', '**/*_test.rs'],
    alwaysApply: false,
    tags: ['test', 'rust'],
    content: `## Rust Testing Guidelines
- Keep unit tests in the same module under \`#[cfg(test)]\`; use \`tests/\` for integration tests.
- Prefer table-driven tests via \`#[test]\` + loops or \`rstest\` when available.
- Assert on \`Result::unwrap()\`/error variants, never on debug formatting.`
  },
  {
    id: 'security',
    title: 'Rust Safety & Untrusted Input',
    description: 'Memory safety, unsafe blocks and input validation',
    alwaysApply: true,
    tags: ['security', 'rust'],
    content: `## Rust Security Guidelines
- Treat \`unsafe\` as a last resort and document every safety invariant.
- Validate and bound all external input before indexing or slicing.
- Use vetted crates for parsing; avoid \`unwrap()\` on user-controlled data.`
  }
];

export const JAVA_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'Java Conventions & Naming',
    description: 'Effective Java conventions, naming and immutability',
    alwaysApply: true,
    tags: ['java', 'style'],
    content: `## Java Style Guidelines
- Classes are \`PascalCase\`, methods/fields \`camelCase\`, constants \`UPPER_SNAKE_CASE\`.
- Prefer immutable value objects and \`record\` types over mutable POJOs.
- Declare \`final\` on fields that are never reassigned; avoid \`static mutable\` state.
- Keep methods short and cohesive; extract early-return guards.`
  },
  {
    id: 'testing-standards',
    title: 'Java Testing (JUnit 5)',
    description: 'JUnit 5 and Mockito conventions',
    globs: ['**/src/test/**/*.java'],
    alwaysApply: false,
    tags: ['test', 'java'],
    content: `## Java Testing Guidelines
- One behaviour per \`@Test\`; name tests after the behaviour, not the method.
- Use \`@ParameterizedTest\` for boundary matrices and \`assertThat\` from AssertJ.
- Never perform real network or filesystem I/O in unit tests.`
  },
  {
    id: 'security',
    title: 'Java Security',
    description: 'Injection prevention and dependency hygiene',
    alwaysApply: true,
    tags: ['security', 'java'],
    content: `## Java Security Guidelines
- Use \`PreparedStatement\`/JPA parameters - never string-concatenate SQL.
- Validate untrusted input with Jakarta Bean Validation at the boundary.
- Do not log secrets, tokens, or full PII payloads.`
  }
];

export const KOTLIN_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'Kotlin Idioms',
    description: 'Idiomatic Kotlin, null-safety and coroutine style',
    alwaysApply: true,
    tags: ['kotlin', 'style'],
    content: `## Kotlin Style Guidelines
- Treat the type system as null safety: no \`!!\` outside tests and platform interop.
- Prefer \`val\` + immutable collections, \`when\` over chained \`if/else\`.
- Use structured concurrency: expose \`suspend\` functions and \`Flow\`, never raw \`GlobalScope\`.`
  },
  {
    id: 'testing-standards',
    title: 'Kotlin Testing',
    description: 'kotlin.test and coroutine test conventions',
    globs: ['**/src/test/**/*.kt'],
    alwaysApply: false,
    tags: ['test', 'kotlin'],
    content: `## Kotlin Testing Guidelines
- Use \`kotlin.test\` assertions and \`runTest\` for coroutine scopes.
- Inject fakes instead of mocking final classes.`
  },
  {
    id: 'security',
    title: 'Kotlin Security',
    description: 'Input validation and safe Android/iOS APIs',
    alwaysApply: true,
    tags: ['security', 'kotlin'],
    content: `## Kotlin Security Guidelines
- Validate and sanitise all IPC and deep-link inputs.
- Never hardcode API keys in \`BuildConfig\`; read them from the environment.`
  }
];

export const PHP_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'PHP Standards (PSR-12)',
    description: 'PSR-12 formatting, strict types and modern PHP',
    alwaysApply: true,
    tags: ['php', 'psr12', 'style'],
    content: `## PHP Style Guidelines
- \`declare(strict_types=1);\` at the top of every file.
- Follow PSR-12; run \`php-cs-fixer\` and \`phpstan\` in CI.
- Prefer constructor property promotion, enums over class constants, and readonly properties.`
  },
  {
    id: 'testing-standards',
    title: 'PHP Testing (PHPUnit)',
    description: 'PHPUnit 10+ conventions',
    globs: ['tests/**/*.php'],
    alwaysApply: false,
    tags: ['test', 'phpunit'],
    content: `## PHP Testing Guidelines
- One test class per subject under \`tests/\`, named \`*Test.php\`.
- Use data providers instead of copy-pasted test methods.`
  },
  {
    id: 'security',
    title: 'PHP Security',
    description: 'Injection, XSS and dependency safety',
    alwaysApply: true,
    tags: ['security', 'php'],
    content: `## PHP Security Guidelines
- Use PDO prepared statements exclusively.
- Escape on output (\`htmlspecialchars\`) and never \`eval\` user input.
- Run \`composer audit\` and pin dependency versions.`
  }
];

export const RUBY_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'Ruby Style',
    description: 'Idiomatic Ruby, RuboCop compliance',
    alwaysApply: true,
    tags: ['ruby', 'style'],
    content: `## Ruby Style Guidelines
- Two-space indentation, \`snake_case\` methods, \`PascalCase\` classes.
- Prefer \`frozen_string_literal: true\` magic comments and immutability.
- Keep \`rubocop\` clean; no \`rescue => e\` without using \`e\`.`
  },
  {
    id: 'testing-standards',
    title: 'Ruby Testing (RSpec)',
    description: 'RSpec conventions',
    globs: ['spec/**/*.rb'],
    alwaysApply: false,
    tags: ['test', 'rspec'],
    content: `## RSpec Guidelines
- One \`describe\` per unit, \`it\` phrased as an expectation.
- Use \`let\` for setup, avoid \`before(:all)\` (order coupling).`
  },
  {
    id: 'security',
    title: 'Ruby Security',
    description: 'Rails strong parameters and secret handling',
    alwaysApply: true,
    tags: ['security', 'ruby'],
    content: `## Ruby Security Guidelines
- Use strong parameters; never \`permit!\` or mass-assign raw params.
- Read secrets from \`Rails.application.credentials\` / ENV, never commit them.`
  }
];

export const DOTNET_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'C# & .NET Conventions',
    description: 'Modern C# style, nullable reference types and LINQ discipline',
    alwaysApply: true,
    tags: ['csharp', 'dotnet', 'style'],
    content: `## C# Style Guidelines
- Enable and respect \`<Nullable>enable</Nullable>\`.
- Prefer \`var\` when the type is obvious, explicit types at API boundaries.
- Use \`async/await\` all the way; never \`.Result\` or \`.Wait()\` on a Task.`
  },
  {
    id: 'testing-standards',
    title: 'C# Testing (xUnit)',
    description: 'xUnit conventions',
    globs: ['**/*.Tests.csproj'],
    alwaysApply: false,
    tags: ['test', 'xunit'],
    content: `## xUnit Guidelines
- One fact per behaviour; use \`[Theory]\` with \`[InlineData]\` for matrices.
- Use \`WebApplicationFactory\` for integration tests.`
  },
  {
    id: 'security',
    title: '.NET Security',
    description: 'Data protection, auth and injection safety',
    alwaysApply: true,
    tags: ['security', 'dotnet'],
    content: `## .NET Security Guidelines
- Use parameterised EF Core queries / stored procedures.
- Use ASP.NET Core Data Protection for tokens; never store them in config.`
  }
];

export const SWIFT_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'Swift Style & API Design',
    description: 'Swift API design guidelines and SwiftLint compliance',
    alwaysApply: true,
    tags: ['swift', 'style'],
    content: `## Swift Style Guidelines
- \`let\` by default, \`guard let\` for unwrapping, no \`force unwrap\` outside UIKit boundaries.
- Mark types \`Sendable\` when crossing concurrency domains.
- Prefer \`Result\`/throws over optional-returning fallible APIs.`
  },
  {
    id: 'testing-standards',
    title: 'Swift Testing',
    description: 'XCTest / swift-testing conventions',
    globs: ['**/Tests/**/*.swift'],
    alwaysApply: false,
    tags: ['test', 'swift'],
    content: `## Swift Testing Guidelines
- Name tests \`test<Subject><Behaviour>()\`; use \`@Test\` with swift-testing where available.`
  },
  {
    id: 'security',
    title: 'iOS/macOS Security',
    description: 'Keychain, entitlements and transport security',
    alwaysApply: true,
    tags: ['security', 'swift'],
    content: `## iOS Security Guidelines
- Store secrets in the Keychain, never in \`UserDefaults\` or the bundle.
- Enforce ATS and pin TLS where possible.`
  }
];

export const ELIXIR_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'Elixir Conventions',
    description: 'Idiomatic Elixir, supervision trees and pattern matching',
    alwaysApply: true,
    tags: ['elixir', 'style'],
    content: `## Elixir Style Guidelines
- Use pattern matching and \`with\` instead of nested conditionals.
- Every process must be supervised; start children under a supervisor.
- Keep modules small and namespaced per context.`
  },
  {
    id: 'testing-standards',
    title: 'Elixir Testing (ExUnit)',
    description: 'ExUnit conventions',
    globs: ['test/**/*.exs'],
    alwaysApply: false,
    tags: ['test', 'exunit'],
    content: `## ExUnit Guidelines
- One \`test\` per behaviour; use \`async: true\` when no shared state.
- Prefer \`Mox\`/doubles over mocking modules.`
  },
  {
    id: 'security',
    title: 'Elixir / Phoenix Security',
    description: 'Web security and secret handling',
    alwaysApply: true,
    tags: ['security', 'elixir'],
    content: `## Phoenix Security Guidelines
- Use Ecto changesets for all input validation; no \`Ecto.Adapters.SQL.query!\` with interpolation.
- Read secrets from \`config/runtime.exs\` environment.`
  }
];

const STACK_ALIASES: Record<string, Stack> = {
  typescript: 'typescript',
  ts: 'typescript',
  node: 'typescript',
  javascript: 'javascript',
  js: 'javascript',
  python: 'python',
  py: 'python',
  go: 'go',
  golang: 'go',
  rust: 'rust',
  rs: 'rust',
  cargo: 'rust',
  java: 'java',
  kotlin: 'kotlin',
  kt: 'kotlin',
  php: 'php',
  ruby: 'ruby',
  rb: 'ruby',
  dotnet: 'dotnet',
  csharp: 'dotnet',
  cs: 'dotnet',
  swift: 'swift',
  elixir: 'elixir',
  ex: 'elixir',
  generic: 'generic'
};

const STACK_RULES: Record<Stack, CanonicalRule[]> = {
  typescript: TYPESCRIPT_RULES,
  javascript: INITIAL_RULES,
  python: PYTHON_RULES,
  go: GO_RULES,
  rust: RUST_RULES,
  java: JAVA_RULES,
  kotlin: KOTLIN_RULES,
  php: PHP_RULES,
  ruby: RUBY_RULES,
  dotnet: DOTNET_RULES,
  swift: SWIFT_RULES,
  elixir: ELIXIR_RULES,
  generic: INITIAL_RULES
};

const STACK_ARCHITECTURE: Partial<Record<Stack, string>> = {
  typescript: `## Technology Stack
- **Runtime:** Node.js 20+ (ESM)
- **Language:** TypeScript (strict mode)
- **Build:** tsup / esbuild
- **Tests:** Node.js native test runner`,
  javascript: `## Technology Stack
- **Runtime:** Node.js 20+ (ESM) or modern browser
- **Language:** JavaScript (ESM)
- **Tests:** (fill in)`,
  python: `## Technology Stack
- **Runtime:** Python 3.11+
- **Tooling:** (uv | poetry | pipx)
- **Typing:** PEP 484 type hints
- **Tests:** pytest`,
  go: `## Technology Stack
- **Runtime:** Go 1.22+
- **Module:** (fill in)
- **Tests:** \`go test ./...\` (with \`-race\` in CI)`,
  rust: `## Technology Stack
- **Runtime:** Rust 1.75+ (stable)
- **Build:** cargo
- **Lint:** clippy + rustfmt
- **Tests:** \`cargo test\``,
  java: `## Technology Stack
- **Runtime:** Java 17+ (LTS)
- **Build:** Gradle or Maven
- **Tests:** JUnit 5`,
  kotlin: `## Technology Stack
- **Runtime:** JVM 17+ / Android
- **Language:** Kotlin
- **Build:** Gradle Kotlin DSL
- **Tests:** kotlin.test`,
  php: `## Technology Stack
- **Runtime:** PHP 8.3+
- **Framework:** (Laravel | Symfony | none)
- **Tests:** PHPUnit 10+`,
  ruby: `## Technology Stack
- **Runtime:** Ruby 3.3+
- **Framework:** (Rails | Sinatra | none)
- **Tests:** RSpec`,
  dotnet: `## Technology Stack
- **Runtime:** .NET 8+
- **Language:** C# with nullable reference types
- **Tests:** xUnit`,
  swift: `## Technology Stack
- **Runtime:** Swift 5.9+ / SwiftUI
- **Tests:** XCTest or swift-testing`,
  elixir: `## Technology Stack
- **Runtime:** Elixir 1.16+ / OTP 26+
- **Framework:** (Phoenix | none)
- **Tests:** ExUnit`
};

/** Normalises a user-supplied stack string, defaulting to `generic`. */
export function normalizeStack(stack?: string): Stack {
  if (!stack) return 'generic';
  return STACK_ALIASES[stack.trim().toLowerCase()] ?? 'generic';
}

/** All stacks that `syncytium init --template` accepts. */
export function listSupportedStacks(): Stack[] {
  return Object.keys(STACK_RULES) as Stack[];
}

export function getRulesForStack(stack: string = 'generic'): CanonicalRule[] {
  return STACK_RULES[normalizeStack(stack)];
}

export function getArchitectureForStack(stack: string = 'generic', projectName = 'This Project'): string {
  const normalized = normalizeStack(stack);
  const stackBlock = STACK_ARCHITECTURE[normalized] ?? '';
  return `# System Architecture & Technology Stack

> Seeded by \`syncytium init --template ${normalized}\` for **${projectName}**. Edit freely - this file is the source of truth.

## Overview
Describe the purpose of this project, its primary architectural patterns, and its system boundaries.

${stackBlock}

## Directory Layout
- \`src/\`: Source code and adapters
- \`.syncytium/\`: Single Source of Truth (SSoT) for all AI agents
  - \`rules/\`: Universal coding and architecture rules
  - \`memory/\`: Architectural decisions (ADRs), handoff history, agent lock
  - \`HANDOFF.md\`: Live agent state and task handoff
`;
}
