import type { CanonicalRule, MemoryDecision, HandoffState } from './types.js';

export const DEFAULT_CONFIG = {
  version: '1.0.0',
  projectName: 'MyProject',
  enabledAdapters: [
    'cursor',
    'claude',
    'copilot',
    'cline',
    'antigravity',
    'windsurf',
    'trae',
    'opencode'
  ],
  options: {
    addSyncytiumBanner: true,
    preserveCustomSections: true
  }
};

export const INITIAL_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'Code Style & Formatting',
    description: 'Enforce clean, readable, modern standards across the project',
    alwaysApply: true,
    tags: ['style', 'typescript', 'formatting'],
    content: `## Code Style Guidelines
- Write clean, modular, and self-documenting code.
- Always prefer strict types, immutable data structures, and pure functions where reasonable.
- Keep functions concise with a single responsibility.
- Preserve existing comments and documentation unless explicitly asked to modify them.
- Avoid unnecessary dependencies; prefer standard library APIs where possible.`
  },
  {
    id: 'testing-standards',
    title: 'Testing Standards & Verification',
    description: 'Quality assurance and test verification guidelines',
    globs: ['**/*.test.ts', '**/*.test.tsx', '**/*.spec.ts', 'tests/**/*'],
    alwaysApply: false,
    tags: ['test', 'quality'],
    content: `## Testing Guidelines
- Write unit tests for all business logic and edge cases.
- Mock external network requests, timers, and heavy I/O in unit test suites.
- Verify tests pass before completing any implementation task.
- Follow the Arrange-Act-Assert pattern for test clarity.`
  },
  {
    id: 'security',
    title: 'Security & Safe Coding',
    description: 'Security rules, secrets handling, and sanitization',
    alwaysApply: true,
    tags: ['security', 'compliance'],
    content: `## Security Guidelines
- Never commit secrets, API keys, tokens, or credentials into source control.
- Validate all incoming user input and payloads against strong schemas (e.g. Zod).
- Prevent injection attacks (SQL, command execution, XSS, template injection).
- Use parameterized queries and sanitized HTML output.`
  }
];

export const INITIAL_ARCHITECTURE = `# System Architecture & Technology Stack

## Overview
Briefly describe the purpose of this project, primary architectural patterns, and system boundaries.

## Technology Stack
- **Runtime:** Node.js (ESM) / TypeScript
- **Frameworks:** Core libraries & CLI
- **Communication:** Model Context Protocol (MCP), File Watchers, Markdown Bridges

## Directory Layout
- \`src/\`: Source code and adapters
- \`.syncytium/\`: Single Source of Truth (SSoT) for all AI agents
  - \`rules/\`: Universal coding and architecture rules
  - \`memory/\`: Architectural decisions (ADRs) and domain knowledge
  - \`HANDOFF.md\`: Live agent state and task handoff
`;

export const INITIAL_DECISIONS: MemoryDecision[] = [
  {
    id: 'ADR-001',
    title: 'Adopt SyncytiumMD as Universal Context Bridge',
    status: 'accepted',
    date: new Date().toISOString().split('T')[0],
    context: 'Multiple AI agents and IDEs (Cursor, Claude Code, Copilot, Cline, Antigravity, etc.) are used concurrently, leading to fragmented context and duplicated rules.',
    decision: 'Use SyncytiumMD as the single source of truth (.syncytium/) to transpile and synchronize rules, memories, and handoff state across all AI coding tools.',
    consequences: 'All tools stay in sync with zero manual copy-pasting. Changes in rules propagate automatically to all connected IDEs and CLIs.'
  }
];

export const INITIAL_HANDOFF: HandoffState = {
  activeAgent: 'Human',
  nextAgent: 'Any AI Assistant (Cursor, Claude Code, Cline, Antigravity, etc.)',
  status: 'ready_for_review',
  goal: 'Initialize project structure and verify multi-agent Markdown bridges',
  completedWork: [
    'Initialized .syncytium/ single source of truth directory',
    'Created core rules: code style, testing, security',
    'Configured default adapters for Cursor, Claude, Copilot, Cline, Antigravity, Windsurf, Trae, and OpenCode'
  ],
  pendingTasks: [
    'Run `npx syncytium sync` or `npm run sync` to generate bridge files',
    'Verify generated rule files across IDEs and CLIs',
    'Update HANDOFF.md when switching between AI assistants'
  ],
  touchedFiles: [
    '.syncytium/syncytium.config.json',
    '.syncytium/rules/code-style.md',
    '.syncytium/rules/security.md',
    '.syncytium/rules/testing-standards.md',
    '.syncytium/architecture.md',
    '.syncytium/memory/decisions.md',
    '.syncytium/HANDOFF.md'
  ],
  contextNotes: 'SyncytiumMD is initialized and ready. All AI agents reading this file should check pending tasks and update this file before ending their turn.',
  lastUpdated: new Date().toISOString()
};

export const BANNER_TEXT = `<!--
  ⚠️ AUTO-GENERATED BY SYNCYTIUM-MD ⚠️
  This file is automatically synchronized from .syncytium/
  Do not edit manually unless you plan to run reverse-sync.
  Source of truth: .syncytium/
-->
`;

export const CI_WORKFLOW_TEMPLATE = `name: SyncytiumMD Verification

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  verify:
    name: Lint & Context Drift Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Syncytium
        run: npm install -g syncytium-md

      - name: Validate Rules (Lint)
        run: syncytium lint

      - name: Verify Zero Context Drift (Diff)
        run: syncytium diff
`;

export const TYPESCRIPT_RULES: CanonicalRule[] = [
  ...INITIAL_RULES,
  {
    id: 'typescript-strictness',
    title: 'TypeScript Strict Mode & Types',
    description: 'Enforce strict TypeScript compiler options and clean type definitions',
    globs: ['**/*.ts', '**/*.tsx'],
    alwaysApply: false,
    tags: ['typescript', 'typing'],
    content: `## TypeScript Guidelines
- Enable and adhere to \`strict: true\` in tsconfig.
- Avoid using \`any\`; prefer \`unknown\`, generic type parameters, or explicit interfaces.
- Define explicit return types for public exported functions and API boundaries.
- Leverage Discriminated Unions for state management and error returns.`
  }
];

export const PYTHON_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'Python Code Style (PEP 8 & Modern Standards)',
    description: 'Enforce PEP 8, Black formatting, and modern typing standards',
    alwaysApply: true,
    tags: ['python', 'pep8', 'style'],
    content: `## Python Code Style Guidelines
- Strictly adhere to PEP 8 standards with 4-space indentation.
- Always include type hints (PEP 484) on function signatures.
- Prefer Python 3.10+ modern syntax (e.g. \`int | None\` instead of \`Optional[int]\`).
- Keep modules focused with explicit \`__all__\` exports where applicable.`
  },
  {
    id: 'testing-standards',
    title: 'Python Testing (pytest)',
    description: 'Testing guidelines for pytest suites',
    globs: ['tests/**/*.py', '**/*_test.py', 'test_*.py'],
    alwaysApply: false,
    tags: ['test', 'pytest'],
    content: `## Testing Guidelines (pytest)
- Structure tests using pytest fixtures and test functions prefixed with \`test_\`.
- Use \`pytest.mark.parametrize\` for boundary and edge-case testing.
- Never make live network requests in unit tests; use pytest-mock or responses.`
  },
  {
    id: 'security',
    title: 'Security & Sanitization',
    description: 'Safe python coding and environment variable practices',
    alwaysApply: true,
    tags: ['security', 'python'],
    content: `## Python Security Guidelines
- Load credentials via \`os.environ\` or \`pydantic-settings\`; never hardcode secrets.
- Avoid \`eval()\`, \`exec()\`, or unsafe \`yaml.load()\` (always use \`safe_load\`).
- Sanitize SQL queries with parameterized ORM bindings.`
  }
];

export const GO_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'Go Idiomatic Standards',
    description: 'Idiomatic Go style and error handling practices',
    alwaysApply: true,
    tags: ['go', 'golang', 'style'],
    content: `## Go Style Guidelines
- Follow standard Go formatting (\`gofmt\` / \`goimports\`).
- Explicit error handling: check errors immediately, do not ignore \`err\`.
- Keep package APIs minimal and package names concise and lowercase.
- Use context.Context as the first argument in long-running or network functions.`
  },
  {
    id: 'testing-standards',
    title: 'Go Testing Standards',
    description: 'Unit and table-driven testing in Go',
    globs: ['**/*_test.go'],
    alwaysApply: false,
    tags: ['test', 'go'],
    content: `## Go Testing Guidelines
- Use table-driven tests with \`t.Run()\` subtests.
- Clean up resources with \`t.Cleanup()\`.
- Verify race conditions using \`go test -race ./...\`.`
  },
  {
    id: 'security',
    title: 'Security & Concurrency',
    description: 'Safe concurrency and credential handling in Go',
    alwaysApply: true,
    tags: ['security', 'concurrency'],
    content: `## Go Security & Safety
- Guard concurrent state with sync.Mutex, sync.RWMutex, or channels.
- Avoid goroutine leaks by always respecting context cancellation.`
  }
];

export function getRulesForStack(stack: string = 'generic'): CanonicalRule[] {
  switch (stack.toLowerCase()) {
    case 'typescript':
    case 'ts':
    case 'node':
    case 'javascript':
    case 'js':
      return TYPESCRIPT_RULES;
    case 'python':
    case 'py':
      return PYTHON_RULES;
    case 'go':
    case 'golang':
      return GO_RULES;
    default:
      return INITIAL_RULES;
  }
}
