import type { CanonicalRule, MemoryDecision, HandoffState } from './types.js';

export const DEFAULT_CONFIG = {
  version: '1.0.0',
  projectName: 'MyProject',
  enabledAdapters: [
    'cursor',
    'claude',
    'copilot',
    'cline',
    'antigravity',
    'windsurf',
    'trae',
    'opencode'
  ],
  options: {
    addSyncytiumBanner: true,
    preserveCustomSections: true
  }
};

export const INITIAL_RULES: CanonicalRule[] = [
  {
    id: 'code-style',
    title: 'Code Style & Formatting',
    description: 'Enforce clean, readable, modern standards across the project',
    alwaysApply: true,
    tags: ['style', 'typescript', 'formatting'],
    content: `## Code Style Guidelines
- Write clean, modular, and self-documenting code.
- Always prefer strict types, immutable data structures, and pure functions where reasonable.
- Keep functions concise with a single responsibility.
- Preserve existing comments and documentation unless explicitly asked to modify them.
- Avoid unnecessary dependencies; prefer standard library APIs where possible.`
  },
  {
    id: 'testing-standards',
    title: 'Testing Standards & Verification',
    description: 'Quality assurance and test verification guidelines',
    globs: ['**/*.test.ts', '**/*.test.tsx', '**/*.spec.ts', 'tests/**/*'],
    alwaysApply: false,
    tags: ['test', 'quality'],
    content: `## Testing Guidelines
- Write unit tests for all business logic and edge cases.
- Mock external network requests, timers, and heavy I/O in unit test suites.
- Verify tests pass before completing any implementation task.
- Follow the Arrange-Act-Assert pattern for test clarity.`
  },
  {
    id: 'security',
    title: 'Security & Safe Coding',
    description: 'Security rules, secrets handling, and sanitization',
    alwaysApply: true,
    tags: ['security', 'compliance'],
    content: `## Security Guidelines
- Never commit secrets, API keys, tokens, or credentials into source control.
- Validate all incoming user input and payloads against strong schemas (e.g. Zod).
- Prevent injection attacks (SQL, command execution, XSS, template injection).
- Use parameterized queries and sanitized HTML output.`
  }
];

export const INITIAL_ARCHITECTURE = `# System Architecture & Technology Stack

## Overview
Briefly describe the purpose of this project, primary architectural patterns, and system boundaries.

## Technology Stack
- **Runtime:** Node.js (ESM) / TypeScript
- **Frameworks:** Core libraries & CLI
- **Communication:** Model Context Protocol (MCP), File Watchers, Markdown Bridges

## Directory Layout
- \`src/\`: Source code and adapters
- \`.syncytium/\`: Single Source of Truth (SSoT) for all AI agents
  - \`rules/\`: Universal coding and architecture rules
  - \`memory/\`: Architectural decisions (ADRs) and domain knowledge
  - \`HANDOFF.md\`: Live agent state and task handoff
`;

export const INITIAL_DECISIONS: MemoryDecision[] = [
  {
    id: 'ADR-001',
    title: 'Adopt SyncytiumMD as Universal Context Bridge',
    status: 'accepted',
    date: new Date().toISOString().split('T')[0],
    context: 'Multiple AI agents and IDEs (Cursor, Claude Code, Copilot, Cline, Antigravity, etc.) are used concurrently, leading to fragmented context and duplicated rules.',
    decision: 'Use SyncytiumMD as the single source of truth (.syncytium/) to transpile and synchronize rules, memories, and handoff state across all AI coding tools.',
    consequences: 'All tools stay in sync with zero manual copy-pasting. Changes in rules propagate automatically to all connected IDEs and CLIs.'
  }
];

export const INITIAL_HANDOFF: HandoffState = {
  activeAgent: 'Human',
  nextAgent: 'Any AI Assistant (Cursor, Claude Code, Cline, Antigravity, etc.)',
  status: 'ready_for_review',
  goal: 'Initialize project structure and verify multi-agent Markdown bridges',
  completedWork: [
    'Initialized .syncytium/ single source of truth directory',
    'Created core rules: code style, testing, security',
    'Configured default adapters for Cursor, Claude, Copilot, Cline, Antigravity, Windsurf, Trae, and OpenCode'
  ],
  pendingTasks: [
    'Run `npx syncytium sync` or `npm run sync` to generate bridge files',
    'Verify generated rule files across IDEs and CLIs',
    'Update HANDOFF.md when switching between AI assistants'
  ],
  touchedFiles: [
    '.syncytium/syncytium.config.json',
    '.syncytium/rules/code-style.md',
    '.syncytium/rules/security.md',
    '.syncytium/rules/testing-standards.md',
    '.syncytium/architecture.md',
    '.syncytium/memory/decisions.md',
    '.syncytium/HANDOFF.md'
  ],
  contextNotes: 'SyncytiumMD is initialized and ready. All AI agents reading this file should check pending tasks and update this file before ending their turn.',
  lastUpdated: new Date().toISOString()
};

export const BANNER_TEXT = `<!--
  ⚠️ AUTO-GENERATED BY SYNCYTIUM-MD ⚠️
  This file is automatically synchronized from .syncytium/
  Do not edit manually unless you plan to run reverse-sync.
  Source of truth: .syncytium/
-->
`;
